#!/bin/sh

# This plugin checks whether there are updates available for the
# installed version of FreeBSD.
# Version 1.1
# Requires FreeBSD 10.0 or later.

# Copyright (c) 2015, Fredrik Lennmark <fredrik@min-hemsida.net>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
#  Redistributions of source code must retain the above copyright notice, this
#  list of conditions and the following disclaimer.
#
#  Redistributions in binary form must reproduce the above copyright notice, this
#  list of conditions and the following disclaimer in the documentation and/or
#  other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
# ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Get a mirror to use
address="_http._tcp.update.freebsd.org"
server=`host -t srv $address | head -1 | awk '{print $8}' | sed 's/.$//'`

# Determine installed patch release
installed_version=`freebsd-version -uk | tail -1`
echo $installed_version | grep "p" > /dev/null
if [ $? -eq 0 ]; then
  patch_release=`echo $installed_version | awk -F 'p' '{print $2}'`
else
  patch_release=0
fi

# Determine latest patch release
release=`uname -r | awk -F '-' '{print $1"-"$2}'`
arch=`uname -m`
fetchdir=$release/$arch
fetch -q http://$server/$fetchdir/latest.ssl -o /tmp/latest.ssl.$$
fetch -q http://$server/$fetchdir/pub.ssl -o /tmp/pub.ssl.$$
latest_patch_release=`openssl rsautl -pubin -inkey /tmp/pub.ssl.$$ -verify < /tmp/latest.ssl.$$ | awk -F '|' '{print $4}'`
latest_release=$release-p$latest_patch_release

# Clean up
rm -f /tmp/latest.ssl.$$
rm -f /tmp/pub.ssl.$$

# Compare latest patch release with installed patch release
if [ $latest_patch_release -gt $patch_release ]; then
  echo "CRITICAL - FreeBSD update available: installed: $installed_version latest: $latest_release"
  exit 2
else
  echo "OK - No FreeBSD updates available - $installed_version is the latest available"
  exit 0
fi
